dist: xenial
language: python
python:
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
  - "3.8"
  # PyPy versions
  - "pypy3.6-7.1.1"
install:
  - pip install -r test_requirements.txt
script:
  - pytest --cov=erika tests/ --cov-report=html -m 'not hardware'
